### PR TITLE
API at velox level

### PR DESCRIPTION
**Pull request by yma11**
@winningsix please take a look.

### CODE REVIEW

**Comment by yma11** [comment]
@XinDongIntel FYI.

**Comment by winningsix** [comment]
Let's add this to VeloxPlugin.  It's not API for Velox.

**Review by winningsix — COMMENTED** [review]
Offline discussed. Notes captured as below:
API of SW

(optional) PlanNodeConvot: fromSubstrait to PlanNode

exec::Task::Task(
    const std::string& taskId,
    std::shared_ptr<const core::PlanNode> planNode,
    int destination,
    std::shared_ptr<core::QueryCtx> queryCtx,
    ConsumerSupplier consumerSupplier,
    std::function<void(std::exception_ptr)> onError);

exec::Task::start(execTask, maxDrivers);

exec::Task::resume(execTask);

exec::Task::addSplitWithSequence(const core::PlanNodeId& planNodeId,
    exec::Split&& split,
    long sequenceId);

Operator::registerOperator(HybridExecOperator::planNodeTranslator);

Questions: (1) how to use ConsumerSupplier (2) how to exec::Task::addSplitWithSequence (3) How data is retieved and converted (5) Add class name for function API

Example

# For presto cpp
auto plan = PlanConvertor.toVeloxQueryPlan(const protocol::planNode originalPlan)

# For presto cpp
auto plan = PlanConvertor.toVeloxQueryPlan(const SparkPlan originalPlan)

....

**Comment by yma11** [comment]
@winningsix Please take a look further. And [PR](https://github.com/Intel-bigdata/VeloxPlugin/pull/9) is submitted for VeloxPlugin repo.

**Comment by winningsix** [comment]
Thanks @yma11 let's discuss it in your new PR.

**Pull request closed without merging**
