### PR TITLE
fix null type issue and refactor test code

### PR DESCRIPTION
**Pull request by jikunshang**
For filter expressions, omnisci will generate code based on input expr info, see CompareIR.cpp L471. And we will set some column to true which means it's don't contains null value.

### CODE REVIEW

**Comment by jikunshang** [comment]
@Intel-bigdata/bdf-cider-engine @yma11 Please take a review.

**Comment by yma11** [comment]
I see you didn't use PartitionedOutputNode in planBuilder(), so you also changed the CiderExecutionUnitGenerator::transformPlan() to make this work?

**Comment by jikunshang** [comment]
> I see you didn't use PartitionedOutputNode in planBuilder(), so you also changed the CiderExecutionUnitGenerator::transformPlan() to make this work?

Yes, see previous [PR](https://github.com/Intel-bigdata/velox/pull/14/files#diff-21005ca5e633dafedc232904a5beccdd179491fc44e1415e3230913159fa2139R88).

**Comment by yma11** [comment]
I see. For your null type issue, I will revert your change by fixing it in another way. Overall LGTM. :)

**Pull request merged**
